version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    volumes:
      - ./server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"
  consul-demo:
    container_name: consul-demo
    build:
      context: ../docker
      dockerfile: Dockerfile
    image: consul-demo:1.1
    ports:
      - "18085:18085"
    networks:
      - consul
#  consul-client:
#    image: hashicorp/consul:1.10.0
#    container_name: consul-client
#    restart: always
#    volumes:
#      - ./client.json:/consul/config/client.json:ro
#    networks:
#      - consul
#    command: "agent"

networks:
  consul:
    driver: bridge

